export { default as belgieFlag } from "./belgie.png"
export { default as beloruskoFlag } from "./belorusko.png"
export { default as bulharskoFlag } from "./bulharsko.png"
export { default as britanieFlag } from "./britanie.png"
export { default as ceskoFlag } from "./cesko.png"
export { default as chorvatskoFlag } from "./chorvatsko.png"
export { default as danskoFlag } from "./dansko.png"
export {default as estonskoFlag} from "./estonsko.png"
export {default as finskoFlag} from "./finsko.png"
export {default as francieFlag} from "./francie.png"
export {default as holandskoFlag} from "./holandsko.png"
export {default as irskoFlag} from "./irsko.png"
export {default as italieFlag} from "./italie.png"
export {default as litvaFlag} from "./litva.png"
export {default as lotysskoFlag} from "./lotyssko.png"
export {default as lucemburskoFlag} from "./lucembursko.png"
export {default as madarskoFlag} from "./madarsko.png"
export {default as nemeckoFlag} from "./nemecko.png"
export {default as norskoFlag} from "./norsko.png"
export {default as polskoFlag} from "./polsko.png"
export {default as portugalskoFlag} from "./portugalsko.png"
export {default as rakouskoFlag} from "./rakousko.png"
export {default as reckoFlag} from "./recko.png"
export {default as rumunskoFlag} from "./rumunsko.png"
export {default as ruskoFlag} from "./rusko.png"
export {default as slovenskoFlag} from "./slovensko.png"
export {default as slovinskoFlag} from "./slovinsko.png"
export {default as spanelskoFlag} from "./spanelsko.png"
export {default as srbskoFlag} from "./srbsko.png"
export {default as svedskoFlag} from "./svedsko.png"
export {default as svycarskoFlag} from "./svycarsko.png"



